version: '3.7'
services:
  nginx:
    container_name: dev_web_prod
    restart: on-failure
    image: nginx:1.19.8
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/static
    ports:
      - 80:80
    depends_on:
      - web
  web:
    container_name: dev_backend_prod
    build: .
    restart: always
    env_file: dev.env
    command: gunicorn --bind 0.0.0.0:8000 auraApp.wsgi
    volumes:
     - static_volume:/home/AuraApp/assets
    depends_on:
     - db
  db:
    container_name: dev_db_prod
    image: postgres:12.0-alpine
    env_file: dev.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  static_volume:
  postgres_data:

